services:
  dev:
    tty: true
    hostname: devcontainer
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.devcontainer
      pull: true
      args:
        PROJECT_NAME: elin-newgameplus
    volumes:
      # Workspace
      - ..:/workspace/elin-newgameplus:cached
      - /mnt/s/Steam/steamapps/workshop/content/2135150:/mnt/workshop:ro
      - /mnt/s/Steam/steamapps/common/Elin:/mnt/elin:cached
      # Home
      - ../volumes/home:/home/vscode:cached
      # Additional scripts
      - ~/scripts:/home/vscode/scripts:ro
    networks:
      agent-team-bridge-network:
        aliases:
          - elin-newgameplus
networks:
  agent-team-bridge-network:
    name: agent-team-bridge
